#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packages using pip
all flask flask_cors bs4 lxml pelican markdown gevent
pip install flask flask_cors bs4 lxml pelican markdown gevent

